name: distribute

on: [push, pull_request]

jobs:
  build_wheel:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: Install build
        run: pip install build==1.0.3

      - name: Build wheel
        run: python -m build

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist/*.whl