name: ci

on: [push, pull_request]

jobs:
  test_install:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install
        run: pip install .

  linting:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-dev
        run: pip install .[dev]
      - name: black
        run: ./codetools/black/check.sh
      - name: darglint
        run: ./codetools/darglint/check.sh
      - name: isort
        run: ./codetools/isort/check.sh
      - name: mypy
        run: ./codetools/mypy/check.sh
      - name: pydocstyle
        run: ./codetools/pydocstyle/check.sh
      - name: pyflakes
        run: ./codetools/pyflakes/check.sh
      - name: sort-all
        run: |
          ./codetools/sort_all/fix.sh
          [[ -z $(git status -s) ]]
          git checkout -- .

  test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: install-dev
        run: pip install .[dev]
      - name: test
        run: pytest
